name: bigquerry_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.0-163.0.dev <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  http: ^1.2.2
  googleapis_auth: ^1.2.1
  googleapis: ^13.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
